### PR TITLE
Separate the tracker, the state, and the view, + a bunch of other things

### LINKED ISSUE #76: Has the caching system been tested ?
Just in case I overlooked something in #75, did anyone test the caching system in the view ?

Without the `__hash__` function being implemented, two items with identical id will likely not have the same hash, and therefore be duplicated in the set of cached item, which actually means that there is no cache (worse, items from all previous runs are stored !).

Thoughts ?

### LINKED ISSUE #81: Cath and Chest are alternate floor to Sheol and Dark room in Afterbirth
They are not separate floor anymore, so if you run to the dark room the tracker will display "Cath" instead of "Sheol".

I'll have a PR for that with all the other stuff (yeah doing some tests for regressions highlighted a couple of other things :) ).

### PR DESCRIPTION
**Pull request by viroulep**
This PR is not ready yet, it's just a placeholder to track its progression and see if what I'm doing looks good.

Here is a bunch of things I want to address with this : 
- [x] Create a tracker state
- [x] Fully separate Tracker/Game objects/View (with the above it addresses #40 )
- [x] Separate the log parser from the tracker
- [x] Make the options shared by every module
- [x] Export and import game objects to/from json
- [x] Fix #76 
- [x] Fix #81 
- [x] Fix the "log not found" message not displaying properly
- [x] Implement #84
- [ ] Document the new feature
- [ ] Restore the run summary stuff
- [ ] Some code checking/cleaning (partially done with pylint)

And after/during all this some code review to be sure I'm not doing sh*t.

As is this version should run just like the current master. I'll update the PR as I implement stuff, I'll try to always keep it working.

### CODE REVIEW

**Comment by viroulep** [comment]
I finished the object/tracker/view separation, it's my branch 'next' if you want to checkout it.

If someone using Windows is willing to test this I'll be very thankful, as I moved some windows-specific stuff from the tracker to the view. I took extra care when doing that, but I couldn't manage to test it.

I'm not yet quite satisfied with how the view is looking right now, I'll rework it a bit so that it can actually draw a single state additionally to draw it incrementally (and fix #76 on the way).

**Comment by Hyphen-ated** [comment]
it runs and seems to be working for me right now on windows. I haven't finished looking in full detail at the code but it looks really good so far. great job

the release script even still works

**Comment by viroulep** [comment]
Thanks !

I've just pushed a full version.
Once setup, the tracker should be able to fully communicate with the server.

I made a very basic UI for server options but it does the job !
There is a "hidden" debug feature for now : if you hit "Ctrl-C" in the tracker's window, it will output the current state to "../export_state.json".

The tracker should never crash, but rather output errors to the logfile and on the tracker window.
I believe the deserialization mechanism is resistant to dumb values (type and value checking for specific keys), so feel free to feed him with whatever you want :p

Now this just needs some testing and code review !

edit: oh and document the new feature too.

**Comment by sillypears** [comment]
When I used the "ctrl+c" shortcut the tracker crashed and I got this in the tracker_log.txt

Traceback (most recent call last):
  File ".\item_tracker.py", line 161, in main
    rt.run()
  File ".\item_tracker.py", line 80, in run
    done = drawing_tool.handle_events()
  File ".\view_controls\view.py", line 128, in handle_events
    state_file.write(json.dumps(self.state, cls=TrackerStateEncoder,
NameError: global name 'TrackerStateEncoder' is not defined

**Comment by viroulep** [comment]
Oh right, the import is missing...
This :

``` python
from game_objects.state import TrackerStateEncoder
```

at the beginning.

**Comment by sillypears** [comment]
The version I ran has this:

``` python
from game_objects.state  import TrackerState, TrackerStateEncoder
```

at the beginning.

**Comment by viroulep** [comment]
Not in view.py !
Put it there and it should correctly output the json ;)
Not sure if I should commit that as this is a debug feature that should be removed when everything is confirmed to work.

**Comment by sillypears** [comment]
Yea, if that's the case it doesn't even matter :)

**Pull request merged**
